//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WroseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scenario_Details
    {
        public int ID { get; set; }
        public int Project_ID { get; set; }
        public string Scenario_Name { get; set; }
        public int Waste_Tech_ID { get; set; }
        public byte Active { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<byte> IsDefault { get; set; }
    
        public virtual Project_Details Project_Details { get; set; }
        public virtual Waste_tech_Master Waste_tech_Master { get; set; }
    }
}
